title: Comprehensive Test Site
description: Testing GitHub Pages configuration
baseurl: ""
url: "https://username.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - nonexistent-jekyll-plugin-12345

markdown: kramdown
